void main() {
  String ilce = "Türkoğlu";
  String kita = "Asya";
  String faks = "0(212)555-12-34";
  int postaKodu = 46800;
  String instaAdresi = "muhammet_alid";
  String calistiginBolum = "Flutter Developer";
  int urunMiktari = 13;
  String musteriSoyadi = "Divan";
  double odemeMiktari = 13.13;
  String dogumTarihi = "13.01.1999";
  double borc = 99.99;
  bool medeniHali = true;
  String videoYorumu = "Başarılı bir içerik olmuş";
  String odemeSaati = "13.13";
  double eftMiktari = 1313.13;
  int satilanMiktar = 1;
  String telefonModeli = "Xiaomi Redmi Note 10 Pro";
  String dergiAdi = "Eylül";
  String basimTarihi = "23.04.2020";
  double zamMiktari = 46.13;
  int daireSayisi = 46;
  double enlem = 46.9999;
  double boylam = 99.9946;
  String yemekAdi = "Lahmacun";
  double urunFiyati = 99.9;
  String sirket = "Dvn Ltd. Şti.";
  String videoAdi = "Flutter Clean Architecture";
  String muzikSuresi = "9:33";
  String mekanPuani = "4,2";
  String dosyaAdi = "eylül.dart";
  String resimFormati = "jpg";
  String renk = "Yeşil";
  String renkKodu = "#4bc893";
  String bilgisayarModeli = "Asus Rog Strix";
  String ekranBoyutu = "6.1";
  String kullanimSuresi = "3 Ay";
  double basinc = 1.01325;
  String etkinlikGunu = "13 Ocak 2033";
  String odemeGunu = "31.12.2025";
  String yolculukCikisTarihi = "03/06/1453";
  String mahalleAdi = "Gaziosmanpaşa";
  String otobusHatti = "76D";
  String kullanilanDakika = "3:12";
  String kargoTakipNo = "YRT12345678";
  String kuponSuresi = "25-11-2023";
  String kuponKodu = "indirim13";
  String faturaTarihi = "13/12/2023 13:46";

  print("İlçe: $ilce");
  print("Kıta: $kita");
  print("Faks: $faks");
  print("Posta Kodu: $postaKodu");
  print("İnstagram Adresi: $instaAdresi");
  print("Çalıştığın Bölüm: $calistiginBolum");
  print("Ürün Miktarı: $urunMiktari");
  print("Müşteri Soyadı: $musteriSoyadi");
  print("Ödeme Miktarı: $odemeMiktari");
  print("Doğum Tarihi: $dogumTarihi");
  print("Borç: $borc");
  print("Medeni Hali: $medeniHali");
  print("Video Yorumu: $videoYorumu");
  print("Ödeme Saati: $odemeSaati");
  print("EFT Miktarı: $eftMiktari");
  print("Satılan Miktar: $satilanMiktar");
  print("Telefon Modeli: $telefonModeli");
  print("Dergi Adı: $dergiAdi");
  print("Basım Tarihi: $basimTarihi");
  print("Zam Miktarı: $zamMiktari");
  print("Daire Sayısı: $daireSayisi");
  print("Enlem: $enlem");
  print("Boylam: $boylam");
  print("Yemek Adı: $yemekAdi");
  print("Ürün Fiyatı: $urunFiyati");
  print("Şirket: $sirket");
  print("Video Adı: $videoAdi");
  print("Müzik Süresi: $muzikSuresi");
  print("Mekan Puanı: $mekanPuani");
  print("Dosya Adı: $dosyaAdi");
  print("Resim Formatı: $resimFormati");
  print("Renk: $renk");
  print("Renk Kodu: $renkKodu");
  print("Bilgisayar Modeli: $bilgisayarModeli");
  print("Ekran Boyutu: $ekranBoyutu");
  print("Kullanım Süresi: $kullanimSuresi");
  print("Basınç: $basinc");
  print("Etkinlik Günü: $etkinlikGunu");
  print("Ödeme Günü: $odemeGunu");
  print("Yolculuk Çıkış Tarihi: $yolculukCikisTarihi");
  print("Mahalle Adı: $mahalleAdi");
  print("Otobüs Hattı: $otobusHatti");
  print("Kullanılan Dakika: $kullanilanDakika");
  print("Kargo Takip No: $kargoTakipNo");
  print("Kupon Süresi: $kuponSuresi");
  print("Kupon Kodu: $kuponKodu");
  print("Fatura Tarihi: $faturaTarihi");
}
