name: odev3
description: A new Flutter project.



version: 1.0.0+1

environment:
  sdk: '^3.1.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0




flutter:

  uses-material-design: true

  generate: true
  assets:
    - img/

  fonts:
    - family: Pasific
      fonts:
          - asset: font/Pacifico-Regular.ttf

