// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoPEq9PnsNCyK8wObEuRHigQfFCTkFQko',
    appId: '1:369203876505:android:7ecc965391e24642ef1e08',
    messagingSenderId: '369203876505',
    projectId: 'flutterbootcamp-eea9e',
    storageBucket: 'flutterbootcamp-eea9e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrLe8boLxyvHIIeFxri9I_56WNWb45SVI',
    appId: '1:369203876505:ios:13cbcdea656201ffef1e08',
    messagingSenderId: '369203876505',
    projectId: 'flutterbootcamp-eea9e',
    storageBucket: 'flutterbootcamp-eea9e.appspot.com',
    androidClientId: '369203876505-ghsqnphkd4e4bckjdvivsh1aengmq1mt.apps.googleusercontent.com',
    iosClientId: '369203876505-7k0k46othle0j294rc8aiepor16sci00.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodApp',
  );
}
